import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "./components/Navigation";
import { LayoutProvider }from "@/contexts/LayoutContext";
import { GET as getAgencies } from './api/agencies/route';
import { GET as getCorrections } from './api/corrections/route';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const agenciesRes = await getAgencies();
  const agencies = await agenciesRes.json();

  const correctionsRes = await getCorrections();
  const corrections = await correctionsRes.json();

  const data = { agencies, corrections };

  return (
    <html lang="en">
      <body className={` ${inter.className} mt-24`}>
        <LayoutProvider data={data}>
          <Navigation />
          {children}
        </LayoutProvider>
      </body>
    </html>
  );
}
